apiVersion: v1
kind: Pod
metadata:
  name: store-web
  namespace: mysqldev
  labels:
        app: store-web
spec:
  containers:
    - name: store-web
      image: <REGISTRY_NAME>.azurecr.io/store-php
      imagePullPolicy: IfNotPresent
  imagePullSecrets:
    - name: acr-secret